services:
  db:
    image: mysql:8.0
    container_name: db
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - "4001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: unow
      MYSQL_USER: unow
      MYSQL_PASSWORD: unow

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: unow
      WORDPRESS_DB_PASSWORD: unow
      WORDPRESS_DB_NAME: unow
    volumes:
      - ./wp_data:/var/www/html
